### ISSUE TITLE
Add a necessary condition "working in small batches"

### ISSUE THREAD

**Issue by PCorbard** [Minimum-CD/cd-manifesto#181] opened 2022-01-11 12:55 UTC
**Is your proposed change related to a problem? Please describe.**
A clear and concise description of what the problem is. Ex. I don't agree with[...]
=> Working in small batches is described as a necessary condition to continuous integration and trunk-based development in DORA research and Accelerate (see https://cloud.google.com/architecture/devops/devops-process-working-in-small-batches)

**Describe the solution you'd like**
=> Add an item "Working in small batches" in the list of minimum activities for CI 
=> Eventually add it also for the list of minimum activities for CD

**Describe alternatives you've considered**
=> Mention the importance of working in small batches in the introductory text

**Comment by bdfinst** [comment] 2022-01-11 14:17
Duplicate of issue https://github.com/Minimum-CD/cd-manifesto/issues/132.

**Closed by bdfinst** 2022-01-11 14:17 UTC
